#PBS -l nodes=1:ppn=1
#PBS -A bigboss

### default memory ~3.5 GB

### NERSC recommends requesting more like:

###PBS -l pvmem=4GB
###PBS -l pvmem=20GB

##PBS -q serial
##PBS -l pvmem=44GB

#PBS -q reg_xlmem
##PBS -l pvmem=110GB
#PBS -l pvmem=96GB
#PBS -l walltime=24:00:00
#PBS -N wise
#PBS -o data/logs
#PBS -e data/logs

cd ${HOME}/unwise
python -u unwise_coadd.py --outdir data/unwise-4 --dataset allsky --maxmem 110


